CREATE TYPE "tipo_usuario" AS ENUM (
  'administrador',
  'bibliotecario',
  'profesor',
  'alumno'
);

CREATE TYPE "estado_usuario" AS ENUM (
  'activo',
  'suspendido',
  'bloqueado'
);

CREATE TYPE "disponible" AS ENUM (
  'disponible',
  'prestado',
  'reservado',
  'dañado',
  'perdido',
  'obsoleto'
);

CREATE TYPE "estado_prestamo" AS ENUM (
  'activo',
  'vencido',
  'devuelto',
  'perdido'
);

CREATE TYPE "tipo_prestamo" AS ENUM (
  'interno',
  'externo'
);

CREATE TYPE "accion_iso" AS ENUM (
  'crear',
  'actualizar',
  'borrar',
  'prestamo',
  'devolucion',
  'renovacion',
  'pago_multa'
);

CREATE TABLE "usuarios" (
  "id_usuario" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_completo" varchar(150) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "contrasena" varchar(255) NOT NULL,
  "tipo" tipo_usuario NOT NULL,
  "estado" estado_usuario DEFAULT 'activo',
  "matricula_empleado" varchar(20) UNIQUE,
  "creado_en" timestamp DEFAULT (now())
);

CREATE TABLE "editoriales" (
  "id_editorial" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "pais" varchar(100)
);

CREATE TABLE "categorias" (
  "id_categoria" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL
);

CREATE TABLE "libros" (
  "id_libro" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar(255) NOT NULL,
  "autor" varchar(150),
  "isbn" varchar(20) UNIQUE,
  "ficha_bibliografica" text,
  "id_editorial" bigint,
  "id_categoria" bigint
);

CREATE TABLE "ejemplares" (
  "id_ejemplar" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_libro" bigint NOT NULL,
  "codigo_inventario" varchar(50) UNIQUE,
  "ubicacion_pasillo_estante" varchar(100),
  "disponible" disponible DEFAULT 'disponible',
  "precio_compra_usd" decimal(10,2),
  "fecha_adquisicion" date
);

CREATE TABLE "compras_libros" (
  "id_compra" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "proveedor" varchar(150),
  "factura" varchar(100),
  "fecha_compra" date,
  "monto_total" decimal(10,2)
);

CREATE TABLE "compras_detalle" (
  "id_detalle" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_compra" bigint,
  "id_ejemplar" bigint,
  "precio_unitario_usd" decimal(10,2)
);

CREATE TABLE "prestamos" (
  "id_prestamo" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" bigint NOT NULL,
  "id_ejemplar" bigint NOT NULL,
  "tipo" tipo_prestamo NOT NULL,
  "estado" estado_prestamo DEFAULT 'activo',
  "fecha_salida" timestamp DEFAULT (now()),
  "fecha_vencimiento" timestamp NOT NULL,
  "fecha_devolucion" timestamp,
  "renovaciones_conteo" int DEFAULT 0,
  "autorizado_por" bigint,
  "condicion_entrega" varchar(255),
  "condicion_retorno" varchar(255),
  "folio_recibo" varchar(50)
);

CREATE TABLE "multas" (
  "id_multa" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_prestamo" bigint NOT NULL,
  "dias_retraso" int,
  "monto_por_dia" decimal(10,2) DEFAULT 10,
  "monto_total" decimal(10,2),
  "tipo_mora" varchar(50),
  "estado_pago" boolean DEFAULT false,
  "comprobante_tesoreria" varchar(100),
  "creado_en" timestamp DEFAULT (now())
);

CREATE TABLE "bitacora_iso_9001" (
  "id_log" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario_actor" bigint,
  "accion" accion_iso NOT NULL,
  "entidad_afectada" varchar(50),
  "id_entidad_afectada" bigint,
  "detalle_cambio" json,
  "ip_usuario" varchar(50),
  "modulo" varchar(50),
  "creado_en" timestamp DEFAULT (now())
);

CREATE TABLE "integracion_escolar" (
  "id_escolar" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" bigint UNIQUE NOT NULL,
  "matricula_escolar" varchar(20) UNIQUE,
  "carrera" varchar(100),
  "situacion_academica" varchar(50),
  "periodo_activo" boolean DEFAULT true,
  "ultima_sincronizacion" timestamp DEFAULT (now())
);

CREATE TABLE "integracion_rh" (
  "id_rh" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" bigint UNIQUE NOT NULL,
  "numero_empleado" varchar(20) UNIQUE,
  "departamento" varchar(100),
  "puesto" varchar(100),
  "estado_laboral" varchar(50),
  "ultima_sincronizacion" timestamp DEFAULT (now())
);

CREATE TABLE "sincronizacion_tesoreria" (
  "id_sinc" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo_operacion" varchar(50),
  "id_referencia_local" bigint,
  "folio_transaccion_externo" varchar(50) UNIQUE,
  "monto_reportado" decimal(10,2),
  "estado_notificacion" varchar(20) DEFAULT 'enviado',
  "fecha_comunicacion" timestamp DEFAULT (now())
);

CREATE TABLE "calendario_institucional" (
  "id_fecha" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" date UNIQUE,
  "es_laboral" boolean DEFAULT true,
  "descripcion_festivo" varchar(100)
);

COMMENT ON COLUMN "integracion_escolar"."situacion_academica" IS 'Regular, Baja, Egresado';

COMMENT ON COLUMN "integracion_rh"."estado_laboral" IS 'Activo, Incapacidad, Baja';

COMMENT ON COLUMN "sincronizacion_tesoreria"."tipo_operacion" IS 'prestamo, devolucion, multa';

COMMENT ON COLUMN "sincronizacion_tesoreria"."id_referencia_local" IS 'ID de prestamo o multa';

ALTER TABLE "libros" ADD FOREIGN KEY ("id_editorial") REFERENCES "editoriales" ("id_editorial") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "libros" ADD FOREIGN KEY ("id_categoria") REFERENCES "categorias" ("id_categoria") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ejemplares" ADD FOREIGN KEY ("id_libro") REFERENCES "libros" ("id_libro") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prestamos" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prestamos" ADD FOREIGN KEY ("id_ejemplar") REFERENCES "ejemplares" ("id_ejemplar") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "prestamos" ADD FOREIGN KEY ("autorizado_por") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "multas" ADD FOREIGN KEY ("id_prestamo") REFERENCES "prestamos" ("id_prestamo") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sincronizacion_tesoreria" ADD FOREIGN KEY ("id_referencia_local") REFERENCES "multas" ("id_multa") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "compras_detalle" ADD FOREIGN KEY ("id_compra") REFERENCES "compras_libros" ("id_compra") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "compras_detalle" ADD FOREIGN KEY ("id_ejemplar") REFERENCES "ejemplares" ("id_ejemplar") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bitacora_iso_9001" ADD FOREIGN KEY ("id_usuario_actor") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "integracion_escolar" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "integracion_rh" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;
